### ISSUE TITLE
Typo- First Paragraph in Chapter 9

### ISSUE THREAD

**Issue by nadirsidi** [djnavarro/rbook#1]
Great voice, love your sense of humor. Thank you!

It looks like there is a typo at the end of the first paragraph in Chapter 9, on page 275. It currently reads, 

> The bigger and more useful part of statistics is that it provides that let you make inferences about data.

I think the first "that" should perhaps be "what".

**Comment by Maschette** [comment]
I actually think there is a word missing after provides? @djnavarro "that it provides {something} that let[s] you make inferences about data." happy to make either change

**Comment by djnavarro** [comment]
Fixed it to read "provides tools that let you make inferences"
